# Generated by Django 4.2.29 on 2026-03-30 08:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recoleccion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Encuesta')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso en kg')),
                ('talla_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Talla en cm')),
                ('tension_arterial', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tensión Arterial')),
                ('citologia_adn_vph', models.BooleanField(default=False, verbose_name='¿Realización de Citología - ADN VPH?')),
                ('mamografia_ecm', models.BooleanField(default=False, help_text='Incluye mamografía y autoexamen de mama.', verbose_name='¿Realización Mamografía - ECM?')),
                ('tamizaje_ca_colon', models.BooleanField(default=False, verbose_name='¿Realización Tamizaje CA de Colon?')),
                ('tamizaje_ca_prostata', models.BooleanField(default=False, verbose_name='¿Realización Tamizaje CA de Próstata?')),
                ('desparasitacion_antihelmintica', models.BooleanField(default=False, verbose_name='¿Desparasitación Antihelmíntica al día?')),
                ('planificacion_familiar', models.BooleanField(default=False, verbose_name='¿Utiliza algún método de Planificación Familiar?')),
                ('tamizaje_anemia', models.BooleanField(default=False, verbose_name='¿Tamizaje para Anemia?')),
                ('tamizaje_riesgo_cardiovascular', models.BooleanField(default=False, help_text='Incluye laboratorios y exámenes pertinentes.', verbose_name='¿Tamizaje de Riesgo Cardiovascular?')),
                ('vacunacion', models.BooleanField(default=False, verbose_name='¿Esquema de Vacunación completo (RIAS)?')),
                ('valoracion_odontologia', models.BooleanField(default=False, verbose_name='¿Valoración Odontología al día?')),
                ('consulta_control_rias', models.BooleanField(default=False, help_text='Valoración según curso de vida, Resolución 3280.', verbose_name='¿Consulta de Control (RIAS)?')),
                ('laboratorios_rias', models.BooleanField(default=False, verbose_name='¿Toma de Laboratorios según RIA?')),
                ('tamizaje_its', models.BooleanField(default=False, verbose_name='¿Tamizaje para ITS?')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='patients.paciente', verbose_name='Paciente Encuestado')),
            ],
            options={
                'verbose_name': 'Encuesta de Salud',
                'verbose_name_plural': 'Encuestas de Salud',
                'ordering': ['-fecha_recoleccion'],
            },
        ),
        migrations.CreateModel(
            name='PlanCuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situaciones', models.TextField(blank=True, null=True, verbose_name='Situaciones Encontradas')),
                ('prioridad', models.TextField(blank=True, null=True, verbose_name='Prioridad para la Salud')),
                ('intervenciones', models.TextField(blank=True, null=True, verbose_name='Acciones e Intervenciones')),
                ('actividades', models.TextField(blank=True, null=True, verbose_name='Actividades para el Logro')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('encuesta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_cuidado', to='surveys.encuesta')),
            ],
            options={
                'verbose_name': 'Plan de Cuidado',
                'verbose_name_plural': 'Planes de Cuidado',
            },
        ),
    ]
